version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=fabp
      - POSTGRES_PASSWORD=fabp
      - POSTGRES_DATABASE=fabp
    ports:
      - "5432:5432"
    volumes:
      - $PWD/container-data/pgdata:/var/lib/postgresql/data
    container_name: fabp_db

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fabp/app
    container_name: fabp_app
    depends_on:
      - postgres
    volumes:
      - ./src/:/app/src
      - ./bin/:/app/bin
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: on-failure
    command: bash -c "uvicorn src.app:app --host=0.0.0.0 --port=8080 --log-level=debug --reload --reload-dir=./src --use-colors"

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: fabp
