version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=fabp
      - POSTGRES_PASSWORD=fabp
      - POSTGRES_DATABASE=fabp
    ports:
      - "5432:5432"
    volumes:
      - $PWD/container-data/pgdata:/var/lib/postgresql/data
    container_name: fabp_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fabp"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fabp/app
    container_name: fabp_app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/
      - container-data/:/app/container-data
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    restart: on-failure
    command: bash -c "uvicorn app.main:app --host=0.0.0.0 --port=8080 --log-level=debug --reload --reload-dir=./app --use-colors"

volumes:
  container-data:
  pgdata:
    driver: local

networks:
  default:
    name: fabp
